#!/data/data/com.termux/files/usr/bin/bash

read -p "Want to enable \`mv-screenshots\` service now? [yes/y] : " -t10 -n3 isEn
if [[ $isEn == yes || $isEn == y ]] ;then
  [[ -f /data/data/com.termux/files/usr/var/service//mv-screenshots/down ]] && rm /data/data/com.termux/files/usr/var/service//mv-screenshots/down
else
  [[ -f /data/data/com.termux/files/usr/var/service//mv-screenshots/down ]] || touch /data/data/com.termux/files/usr/var/service//mv-screenshots/down
fi

