#!/bin/bash

# scanpackages


#repo_root=
dist_name=stable
comp_name=sh
arch=aarch64
packages_dir=dists/$dist_name/$comp_name/binary-$arch/
mkdir -pv $packages_dir 2>/dev/null

echo dpkg-scanpackages pool/${comp_name}/ /dev/null \> ${packages_dir}Packages
dpkg-scanpackages pool/${comp_name}/ > ${packages_dir}Packages
#gzip -c dists/stable/main/binary-aarch64/Packages > ${packages_dir}/Packages.gz
gzip -k -f $packages_dir/Packages



#cat <<EOF > release.conf
#APT::FTPArchive::Release::Codename "${dist_name}";
#APT::FTPArchive::Release::Origin "TRepo";
#APT::FTPArchive::Release::Components "${comp_name}";
#APT::FTPArchive::Release::Label "TRepo";
#APT::FTPArchive::Release::Architectures "${arch} all";
#EOF


echo "Generating Release file..."
apt-ftparchive -c release/${dist_name}_${comp_name}_${arch}.conf release dists/$dist_name > dists/$dist_name/Release
