#!/bin/bash

# 临时构建目录
BUILD_DIR="build_tmp"
rm -rf "$BUILD_DIR"



# 提取包信息
extract_deb_info() {
  local control_file="$1/DEBIAN/control"
  
  PACKAGE=$(awk '/^Package:/ {print $2}' "$control_file")
  VERSION=$(awk '/^Version:/ {print $2}' "$control_file")
  ARCH=$(awk '/^Architecture:/ {print $2}' "$control_file")


  # 如果没有指定架构，默认为 all
  ARCH="${ARCH:-all}"
}


build_package() {
  local PLATFORM="$2"
  local INSTALL_PREFIX="$3"

  echo "正在构建 [$PLATFORM] 版本..."

  # 1. 准备目录结构 (包含前缀)
  # 普通 Linux: build_tmp/linux/opt/sh
  # Termux:     build_tmp/termux/data/data/.../opt/sh
  local PKG_ROOT="$BUILD_DIR/$PLATFORM"
  local FINAL_DIR="$PKG_ROOT$INSTALL_PREFIX/"

  mkdir -p "$FINAL_DIR"

  echo
  cp -rfvp "$4/DEBIAN/" $PKG_ROOT
  cp -rfvp "$4"/src/* $FINAL_DIR
  echo

  #dpkg-deb --build "$PKG_ROOT" "${PKG_NAME}_${VERSION}_${PLATFORM}.deb"
  extract_deb_info $PKG_ROOT
  local DEB_NAME=${PACKAGE}_${ARCH}_${VERSION}
  #local FIRST_CHAR=${DEB_NAME:0:1}
  #FIRST_CHAR=${FIRST_CHAR,,}
  #local DEB_DIR="$1/$ARCH/$FIRST_CHAR/$PACKAGE"
  local DEB_DIR="$1"
  mkdir -p "$DEB_DIR"
  dpkg-deb --build "$PKG_ROOT" "$DEB_DIR/$DEB_NAME.deb"
}

build_package "$@"
