#!/data/data/com.termux/files/usr/bin/bash


_PKG=${DPKG_MAINTSCRIPT_PACKAGE#service-}
_DIR=$PREFIX/var/service/$_PKG

echo set svlogger
mkdir -pv $_DIR/log
ln -sf $PREFIX/share/termux-services/svlogger $_DIR/log/run &>/dev/null

read -p "Want to enable \`$_PKG\` service now? [N/y] : " -t10 -n1 isEn
if [[ $isEn == y || $isEn == Y ]] ;then
  [[ -f $_DIR/down ]] && rm $_DIR/down
else
  [[ -f $_DIR/down ]] || touch $_DIR/down
fi

