#!/data/data/com.termux/files/usr/bin/bash

read -p "Want to enable \`x11\` service now? [yes/y] : " -t10 -n3 isEn
if [[ $isEn == yes || $isEn == y ]] ;then
  [[ -f /data/data/com.termux/files/usr/var/service//x11/down ]] && rm /data/data/com.termux/files/usr/var/service//x11/down
else
  [[ -f /data/data/com.termux/files/usr/var/service//x11/down ]] || touch /data/data/com.termux/files/usr/var/service//x11/down
fi

